In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from LLS import LLS
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import RidgeCV
from sklearn.metrics import mean_squared_error,mean_absolute_error,root_mean_squared_error

In [2]:
data = pd.read_csv("housePrice.csv")
data.head()

,Area,Room,Parking,Warehouse,Elevator,Address,Price,Price(USD)
0,63,1,True,True,True,Shahran,1.850000e+09,61666.67
1,60,1,True,True,True,Shahran,1.850000e+09,61666.67
2,79,2,True,True,True,Pardis,5.500000e+08,18333.33
3,95,2,True,True,True,Shahrake Qods,9.025000e+08,30083.33
4,123,2,True,True,True,Shahrake Gharb,7.000000e+09,233333.33

In [3]:
#Update Price for 24/09/2026
#Dollar in Iran = 230,000
data["Price"] = data["Price(USD)"].astype(np.float64) * 230
data.head()

,Area,Room,Parking,Warehouse,Elevator,Address,Price,Price(USD)
0,63,1,True,True,True,Shahran,14183334.1,61666.67
1,60,1,True,True,True,Shahran,14183334.1,61666.67
2,79,2,True,True,True,Pardis,4216665.9,18333.33
3,95,2,True,True,True,Shahrake Qods,6919165.9,30083.33
4,123,2,True,True,True,Shahrake Gharb,53666665.9,233333.33

In [4]:
address_data = data.nlargest(5, "Price")
address_data

,Area,Room,Parking,Warehouse,Elevator,Address,Price,Price(USD)
1703,420,4,True,True,True,Zaferanieh,708400000.0,3080000.00
1806,705,5,True,True,False,Abazar,697666665.9,3033333.33
430,400,5,True,True,False,Lavasan,651666665.9,2833333.33
816,680,5,True,True,False,Ekhtiarieh,625600000.0,2720000.00
1329,350,4,True,True,True,Niavaran,617166665.9,2683333.33

In [5]:
#Pre-Process
data["Parking"] = data["Parking"].replace([False, True], [0, 1])
data["Warehouse"] = data["Warehouse"].replace([False, True], [0, 1])
data["Elevator"] = data["Elevator"].replace([False, True], [0, 1])

In [6]:
data.head()

,Area,Room,Parking,Warehouse,Elevator,Address,Price,Price(USD)
0,63,1,1,1,1,Shahran,14183334.1,61666.67
1,60,1,1,1,1,Shahran,14183334.1,61666.67
2,79,2,1,1,1,Pardis,4216665.9,18333.33
3,95,2,1,1,1,Shahrake Qods,6919165.9,30083.33
4,123,2,1,1,1,Shahrake Gharb,53666665.9,233333.33

In [7]:
X = data[["Area", "Room", "Parking", "Warehouse", "Elevator"]].to_numpy(dtype=np.float64)
Y = np.array(data["Price"])

In [8]:
X.shape, Y.shape

((3473, 5), (3473,))

In [9]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((2778, 5), (695, 5), (2778,), (695,))

In [10]:
Y_train = Y_train.reshape(-1, 1)
X_train = np.array(X_train)
X_train.dtype

dtype('float64')

In [11]:
lls = LLS()
lls.fit(X_train, Y_train)

In [12]:
loss_mae = lls.evaluate(X_test, Y_test,metric="mae")
loss_mse = lls.evaluate(X_test, Y_test,metric="mse")
loss_rmse = lls.evaluate(X_test, Y_test,metric="rmse")

In [13]:
print(f"loss mae = {loss_mae}")
print(f"loss mse = {loss_mse}")
print(f"loss rmse = {loss_rmse}")

loss mae = 29792713836.55668
loss mse = 4.0289226805937393e+18
loss rmse = 2007217646.5430298

In [17]:
#LinearRegression
lr = LinearRegression()
lr.fit(X_train, Y_train)
y_pred_lr = lr.predict(X_test)

loss_lr_mae = mean_absolute_error(Y_test, y_pred_lr)
loss_lr_mse = mean_squared_error(Y_test, y_pred_lr)
loss_lr_rmse = root_mean_squared_error(Y_test, y_pred_lr)

In [19]:
print(f"loss mae = {loss_lr_mae}")
print(f"loss mse = {loss_lr_mse}")
print(f"loss rmse = {loss_lr_rmse}")

loss mae = 21515619.280313857
loss mse = 1860834615478396.5
loss rmse = 43137392.311988406

In [18]:
#RidgeCV
rcv = RidgeCV()
rcv.fit(X_train, Y_train)
y_pred_rcv = rcv.predict(X_test)

loss_rcv_mae = mean_absolute_error(Y_test, y_pred_rcv)
loss_rcv_mse = mean_squared_error(Y_test, y_pred_rcv)
loss_rcv_rmse = root_mean_squared_error(Y_test, y_pred_rcv)

In [20]:
print(f"loss mae = {loss_rcv_mae}")
print(f"loss mse = {loss_rcv_mse}")
print(f"loss rmse = {loss_rcv_rmse}")

loss mae = 21489503.99781776
loss mse = 1859642408596972.0
loss rmse = 43123571.38035963

In [ ]:
plt.bar()